#!/bin/bash
# This script auto-build an image file for Raspberry Pi SD card
# -> build standard 2 partitions cards: fat16/ext4 or fat16/btrfs
# -> usage of btrfs for linux root filesytem need custom kernel (default one don't have btrfs build-in)
#    see here : https://www.raspberrypi.org/documentation/linux/kernel/building.md for instruction
#
# you can use it like this :
#     rpi-img-maker BOOT_DIR ROOT_DIR IMAGE_FILE
#
# so directly on a Raspberry Pi:
#     sudo rpi-img-maker /boot / /media/pi/my_usb_key/out.img

# vars
NAME=$(basename $0)

# flags
FORCE=0
BTRFS=0

# parse optionals args
while getopts 'bfh' OPTION
do
    case $OPTION in
    b)
        BTRFS=1
        ;;
    f)
        FORCE=1
        ;;
    h)
        printf "Usage: %s: [-h] [-b] [-f] BOOT_DIR ROOT_DIR IMAGE_FILE\n" $NAME
        printf "\n"
        printf "  -h    print this help message\n"
        printf "  -b    use btrfs file system for 2nd part instead of default ext4\n"
        printf "  -f    write img file even if file already exist\n"
        exit 0
        ;;
    esac
done
shift $(($OPTIND - 1))

# parse fixed args
BOOT_PATH=$1
ROOT_PATH=$2
IMG_FILE=$3

# some checks
[ $EUID -ne 0 ] && { printf "ERROR: $NAME needs to be run by root\n" 1>&2; exit 1; }
[ ! -x "$(command -v mkfs.fat)" ] && { printf "ERROR: mkfs.fat not found\n" 1>&2; exit 1; }
[ ! -x "$(command -v mkfs.ext4)" ] && { printf "ERROR: mkfs.ext4 not found\n" 1>&2; exit 1; }
[ $BTRFS -eq 1 ] && [ ! -x "$(command -v mkfs.btrfs)" ] && { printf "ERROR: mkfs.btrfs not found\n" 1>&2; exit 1; }
[ $# -ne 3 ] && { printf "ERROR: $NAME needs 3 args\n" 1>&2; exit 1; }
[ ! -d $BOOT_PATH ] && { printf "ERROR: BOOT_DIR invalid\n" 1>&2; exit 1; }
[ ! -d $ROOT_PATH ] && { printf "ERROR: ROOT_DIR invalid\n" 1>&2; exit 1; }

if [ -f $IMG_FILE ] && [ $FORCE -ne 1 ]
then
    read -p "WARN: Image file $IMG_FILE already exist, confirm overwrite ? (y/n)" -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit 1
    fi
fi

# detect size need for root filesystem
BOOT_SIZE=$(du -smx $BOOT_PATH | cut -f1)
printf "INFO: boot size $BOOT_SIZE MB\n"
[ $BOOT_SIZE -gt 64 ] && { printf "ERROR: boot dir is oversized (more than 64MB)\n" 1>&2; exit 2; }
ROOT_SIZE=$(du -smx $ROOT_PATH | cut -f1)
printf "INFO: root size $ROOT_SIZE MB\n"
[ $ROOT_SIZE -gt 4096 ] && { printf "ERROR: root dir is oversized (more than 4GB)\n" 1>&2; exit 2; }

# init image file (zero padded)
IMG_SIZE=`expr $ROOT_SIZE + 64 + 512`
printf "INFO: start $IMG_SIZE MB image build, please wait\n"
dd if=/dev/zero of=$IMG_FILE bs=1M count=$IMG_SIZE &> /dev/null || { printf "ERROR: file init error\n" 1>&2; exit 1; }
[ $? -eq 0 ] && printf "INFO: init of file %s OK\n" $IMG_FILE

# create 2 partitions on it (for boot and root fs, a sector is 512 bytes wide)
# first for boot (FAT16): fix 64 MB sized from sector 8192 to 137215
# second for root fs (ext4): from sector 137216 to end of image
printf "INFO: create boot (part1) and root (part2) partitions\n"
parted $IMG_FILE mklabel msdos > /dev/null || { printf "ERROR: make part table error\n" 1>&2; exit 1; }
parted $IMG_FILE mkpart primary fat16 8192s 137215s > /dev/null || { printf "ERROR: make part1 error\n" 1>&2; exit 1; }
parted $IMG_FILE -- mkpart primary ext4 137216s -1s > /dev/null || { printf "ERROR: make part2 error\n" 1>&2; exit 1; }

# boot: map loopback, format, mount, copy, unmount, release loopback
LOOP_BOOT=$(losetup --offset $((512*8192)) --sizelimit $((512*129024)) --show --find $IMG_FILE)
mkfs.fat -n "boot" $LOOP_BOOT > /dev/null && printf "INFO: format part1 in fat OK\n"
MNT_BOOT=$(mktemp -d)
printf "INFO: copy files to part1\n"
mount $LOOP_BOOT $MNT_BOOT && cp -ax $BOOT_PATH/. $MNT_BOOT/. && sync && printf "INFO: copy OK\n"
umount $MNT_BOOT
rmdir $MNT_BOOT
sleep 1
losetup -d $LOOP_BOOT

# root: map loopback, format, mount, copy, unmount, release loopback
LOOP_ROOT=$(losetup --offset $((512*137216)) --show --find $IMG_FILE)
MNT_OPT=''
if [ $BTRFS -eq 1 ]
then
    mkfs.btrfs $LOOP_ROOT > /dev/null && printf "INFO: format part2 in btrfs OK\n"
    MNT_OPT='-o compress'
else
    mkfs.ext4 $LOOP_ROOT > /dev/null && printf "INFO: format part2 in ext4 OK\n"
fi
MNT_ROOT=$(mktemp -d)
printf "INFO: copy files to part2, this can take a long time\n"
mount $MNT_OPT $LOOP_ROOT $MNT_ROOT && cp -ax $ROOT_PATH/. $MNT_ROOT/. && sync && printf "INFO: copy OK\n"
umount $MNT_ROOT
rmdir $MNT_ROOT
sleep 1
losetup -d $LOOP_ROOT

# end message
printf "INFO: %s build (size=%s MB)\n" $IMG_FILE $IMG_SIZE
exit 0
